-- Historical leads import from Gmail/Web3Forms (15 May 2026)
-- 141 leads extracted from inbox by Olesya
-- source=web3forms distinguishes these from future portal/app leads

-- Expand source check constraint to allow 'web3forms'
ALTER TABLE public.api_leads DROP CONSTRAINT IF EXISTS api_leads_source_check;
ALTER TABLE public.api_leads ADD CONSTRAINT api_leads_source_check
  CHECK (source IN ('portal', 'app', 'telegram', 'landing', 'web3forms'));

-- Add unique constraint on email (api_leads table is empty at time of import)
ALTER TABLE public.api_leads ADD CONSTRAINT api_leads_email_unique UNIQUE (email);

INSERT INTO public.api_leads (email, source, interest)
VALUES
  ('abdulfattahnour17@gmail.com', 'web3forms', 'Pleiadian'),
  ('abigail.r.liss@gmail.com', 'web3forms', 'Lemurian'),
  ('ahmedelqorashey@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('alaskagirl71@hotmail.com', 'web3forms', 'Lyran'),
  ('aleksandra.birula@icloud.com', 'web3forms', 'Andromedan'),
  ('alisharoseprofeta0143@gmail.com', 'web3forms', 'Siriusian'),
  ('ameliavl@adinet.com.uy', 'web3forms', 'connection:Frequency Twins'),
  ('amytalent1@gmail.com', 'web3forms', 'Unknown'),
  ('angel.deeptib1007@gmail.com', 'web3forms', 'Pleiadian'),
  ('anielle.ifangousine@hotmail.fr', 'web3forms', 'Siriusian'),
  ('anna@laftbranding.com', 'web3forms', 'Cassiopeian'),
  ('artiles.rita@gmail.com', 'web3forms', 'Unknown'),
  ('avinashshejwal44@gmail.com', 'web3forms', 'Siriusian'),
  ('aznamuhammed8055@gmail.com', 'web3forms', 'connection:Eternal Reflection'),
  ('beautifullybroken062988@gmail.com', 'web3forms', 'Siriusian'),
  ('bernard@compucoach.org', 'web3forms', 'Pleiadian'),
  ('bhumiworld108@gmail.com', 'web3forms', 'Polarisian'),
  ('biancaboie@icloud.com', 'web3forms', 'Cassiopeian'),
  ('biancaeggers28@gmail.com', 'web3forms', 'Unknown'),
  ('bunnymom45@gmail.com', 'web3forms', 'Siriusian'),
  ('candisb12@gmail.com', 'web3forms', 'Lemurian'),
  ('chahiraelwattar09@gmail.com', 'web3forms', 'Siriusian'),
  ('christiangel17@gmail.com', 'web3forms', 'Cassiopeian'),
  ('claudiabthomas@aol.com', 'web3forms', 'Cassiopeian'),
  ('coltforgrave@icloud.com', 'web3forms', 'Siriusian'),
  ('d.moro@embarqmail.com', 'web3forms', 'Pleiadian'),
  ('darshanpal987@gmail.com', 'web3forms', 'Tau Cetian'),
  ('davilalynda9@gmail.com', 'web3forms', 'Siriusian'),
  ('davisjanice580@gmail.com', 'web3forms', 'Pleiadian'),
  ('destone0171@yahoo.com', 'web3forms', 'Lemurian'),
  ('dileepkspothencode@gmail.com', 'web3forms', 'Andromedan'),
  ('divyaaprasads@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('duyguellsc@gmail.com', 'web3forms', 'Siriusian'),
  ('empyreaan.healing@gmail.com', 'web3forms', 'Siriusian'),
  ('essence.alexis@yahoo.com', 'web3forms', 'Siriusian'),
  ('gabyxmeza90@gmail.com', 'web3forms', 'Lemurian'),
  ('geecee028@gmail.com', 'web3forms', 'Lemurian'),
  ('gildacaprara@hotmail.it', 'web3forms', 'Siriusian'),
  ('giljitsy@gmail.com', 'web3forms', 'Cassiopeian'),
  ('guedessu@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('habibimasar99@gmail.com', 'web3forms', 'Andromedan'),
  ('hanabdallova@gmail.com', 'web3forms', 'Herculean'),
  ('heatha921@gmail.com', 'web3forms', 'Lemurian'),
  ('hollowaydimario@gmail.com', 'web3forms', 'Pleiadian'),
  ('homaeldar@gmail.com', 'web3forms', 'Cassiopeian'),
  ('ignatius444333@gmail.com', 'web3forms', 'Siriusian'),
  ('ikvanbatenburg@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('infonatc@yahoo.com', 'web3forms', 'connection:Twin Stars'),
  ('italia.fusco@gmail.com', 'web3forms', 'Siriusian'),
  ('jaidymullens12@gmail.com', 'web3forms', 'Vegan'),
  ('jamesammar@gmail.com', 'web3forms', 'Siriusian'),
  ('jamiejorgensentsosie@gmail.com', 'web3forms', 'Siriusian'),
  ('jeniferweigel100@gmail.com', 'web3forms', 'Andromedan'),
  ('jerseyjean25@gmail.com', 'web3forms', 'Lemurian'),
  ('jjshelnut@gmail.com', 'web3forms', 'Lyran'),
  ('jocelyn.long@hotmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('joxic45180@tatefarm.com', 'web3forms', 'Unknown'),
  ('julian.joly@hotmail.com', 'web3forms', 'connection:Mirror Portals'),
  ('kajsa.krebs@hotmail.com', 'web3forms', 'Siriusian'),
  ('kanishka@wordmonk.in', 'web3forms', 'Tau Cetian'),
  ('kathrynm4492@gmail.com', 'web3forms', 'Siriusian'),
  ('kez8t2@hotmail.co.uk', 'web3forms', 'Cassiopeian'),
  ('kirti.rathod10@yahoo.com', 'web3forms', 'Unknown'),
  ('kittyletayf@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('kriscoch@gmail.com', 'web3forms', 'Siriusian'),
  ('krmnameliachm@gmail.com', 'web3forms', 'Cassiopeian'),
  ('larreavaleriadu@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('lcambrus@icloud.com', 'web3forms', 'Pleiadian'),
  ('lilly2butterfly@gmail.com', 'web3forms', 'Cassiopeian'),
  ('linseydewinter@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('lishiwei0824@hotmail.com', 'web3forms', 'Siriusian'),
  ('loshenee80@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('manalmansoura@hotmail.com', 'web3forms', 'Andromedan'),
  ('mandril2002@gmail.com', 'web3forms', 'Arcturian'),
  ('mariaelizabeth.garcia@gmail.com', 'web3forms', 'Lyran'),
  ('marie.bruendl@hotmail.com', 'web3forms', 'Siriusian'),
  ('martinluftpost@icloud.com', 'web3forms', 'Lemurian'),
  ('marygallagher292@gmail.com', 'web3forms', 'Cassiopeian'),
  ('mattfly33@gmail.com', 'web3forms', 'Siriusian'),
  ('maurizioromeo@email.it', 'web3forms', 'connection:Twin Stars'),
  ('megbeard79@gmail.com', 'web3forms', 'Cassiopeian'),
  ('metamuse2022@gmail.com', 'web3forms', 'connection:Mirror Portals'),
  ('monica.hogberg73@gmail.com', 'web3forms', 'Siriusian'),
  ('monika.siebert@web.de', 'web3forms', 'Siriusian'),
  ('morgan.jennifer76@live.com', 'web3forms', 'Pleiadian'),
  ('moser.mina@gmail.com', 'web3forms', 'Andromedan'),
  ('mr.richard.ortiz@gmail.com', 'web3forms', 'Aldebaran'),
  ('mukeshpatidar405@gmail.com', 'web3forms', 'Unknown'),
  ('n1ns3hm1@gmail.com', 'web3forms', 'Polarisian'),
  ('nacolebeasley74@yahoo.com', 'web3forms', 'Siriusian'),
  ('nalluja04@gmail.com', 'web3forms', 'Cassiopeian'),
  ('ncrawshaw24@hotmail.com', 'web3forms', 'Unknown'),
  ('neta.dolev@mail.huji.ac.il', 'web3forms', 'Siriusian'),
  ('newdreamer77@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('nicole2dutan@gmail.com', 'web3forms', 'Unknown'),
  ('niluhosseini@yahoo.com', 'web3forms', 'Siriusian'),
  ('patefieldjen521@gmail.com', 'web3forms', 'Unknown'),
  ('pia_bernaldez@hotmail.com', 'web3forms', 'Siriusian'),
  ('poojasnachankar91@gmail.com', 'web3forms', 'Tau Cetian'),
  ('projopayne43@gmail.com', 'web3forms', 'Lemurian'),
  ('pwarura@yahoo.com', 'web3forms', 'Unknown'),
  ('queenie520.am@gmail.com', 'web3forms', 'Cassiopeian'),
  ('rashmig669@gmail.com', 'web3forms', 'connection:Celestial Mentor'),
  ('rjrakers71@gmail.com', 'web3forms', 'Arcturian'),
  ('rohikaaeee@gmail.com', 'web3forms', 'Lemurian'),
  ('rollingerne@mail.dk', 'web3forms', 'Cassiopeian'),
  ('romnickgumba@gmai.com', 'web3forms', 'Zeta Reticulan'),
  ('rossana80@yahoo.it', 'web3forms', 'Siriusian'),
  ('rxhngill01@gmail.com', 'web3forms', 'Lemurian'),
  ('sabine.muellerbach@gmx.at', 'web3forms', 'connection:Frequency Twins'),
  ('sananingombam04@gmail.com', 'web3forms', 'Unknown'),
  ('sandyhaize76@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('sarithashaji7777@gmail.com', 'web3forms', 'Pleiadian'),
  ('sebagsylvie@hotmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('shana.kesling@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('sharonhart1@yahoo.com.au', 'web3forms', 'Siriusian'),
  ('sheridanvo@gmail.com', 'web3forms', 'Siriusian'),
  ('slickho42@yahoo.com', 'web3forms', 'Siriusian'),
  ('sofiarvsilva12@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('solcrystal818@gmail.com', 'web3forms', 'Siriusian'),
  ('staceyrbrown369@gmail.com', 'web3forms', 'Siriusian'),
  ('steelgate99@gmail.com', 'web3forms', 'Andromedan'),
  ('stefania.einaudi@gmail.com', 'web3forms', 'Lyran'),
  ('steveeannebates333@gmail.com', 'web3forms', 'Unknown'),
  ('stevenspears101@gmail.com', 'web3forms', 'Zeta Reticulan'),
  ('sydpotadle@gmail.com', 'web3forms', 'Siriusian'),
  ('test@example.com', 'web3forms', 'Test'),
  ('thatgirltheycallgolden@gmail.com', 'web3forms', 'Aldebaran'),
  ('toshine888@gmail.com', 'web3forms', 'Arcturian'),
  ('tyennaoli1@gmail.com', 'web3forms', 'Cassiopeian'),
  ('tyflowerguy@gmail.com', 'web3forms', 'Siriusian'),
  ('ulrike.lerch@lerch.net', 'web3forms', 'Lyran'),
  ('umajoy1998@gmail.com', 'web3forms', 'Siriusian'),
  ('valek.shov@gmail.com', 'web3forms', 'Andromedan'),
  ('valelago02@gmail.com', 'web3forms', 'Cassiopeian'),
  ('veeristheboss@gmail.com', 'web3forms', 'Blue Avian'),
  ('vidyabandol0804@gmail.com', 'web3forms', 'connection:Frequency Twins'),
  ('wisdom.pragya01@gmail.com', 'web3forms', 'Siriusian'),
  ('wsemcclendon@gmail.com', 'web3forms', 'Cassiopeian'),
  ('yogawithevelin@gmail.com', 'web3forms', 'Unknown'),
  ('yoginipraxis@gmail.com', 'web3forms', 'Andromedan')
ON CONFLICT (email) DO NOTHING;

-- Verify: should return total=141
SELECT COUNT(*) AS total, COUNT(interest) AS with_interest FROM public.api_leads WHERE source = 'web3forms';