-- Instagram workshop leads import (Jan–May 2026)
-- 101 unique emails, deduplicated, typos corrected
-- source=instagram: signed up via Instagram free workshop form

-- Add instagram to allowed sources
ALTER TABLE public.api_leads DROP CONSTRAINT IF EXISTS api_leads_source_check;
ALTER TABLE public.api_leads ADD CONSTRAINT api_leads_source_check
  CHECK (source IN ('portal', 'app', 'telegram', 'landing', 'web3forms', 'instagram'));

INSERT INTO public.api_leads (email, source)
VALUES
  ('shilat1993@gmail.com', 'instagram'),
  ('cherlieth@yahoo.com', 'instagram'),
  ('lena.cudna@gmail.com', 'instagram'),
  ('coreymccarthy@outlook.com.au', 'instagram'),
  ('ozge.birozsoy@gmail.com', 'instagram'),
  ('sgavriel@gmail.com', 'instagram'),
  ('tamulipriya85@gmail.com', 'instagram'),
  ('jbsl1mshadyy662344@yahoo.com', 'instagram'),
  ('premysman@hotmail.com', 'instagram'),
  ('hughescheyenne4@gmail.com', 'instagram'),
  ('vanja_lovric@hotmail.com', 'instagram'),
  ('medjedovic.tatjana@gmail.com', 'instagram'),
  ('elisavettzima@gmail.com', 'instagram'),
  ('nikolinkonomi@gmail.com', 'instagram'),
  ('leonard.loth@googlemail.com', 'instagram'),
  ('jerseyjean25@gmail.com', 'instagram'),
  ('azura.lauren@gmail.com', 'instagram'),
  ('umutsariucak@outlook.com', 'instagram'),
  ('jamespierre87@yahoo.com', 'instagram'),
  ('babyangel_400@hotmail.com', 'instagram'),
  ('willburke962@gmail.com', 'instagram'),
  ('windabaeti@gmail.com', 'instagram'),
  ('dragana.zilic.jovanic@gmail.com', 'instagram'),
  ('julia.connortraining@gmail.com', 'instagram'),
  ('yogawithevelin@gmail.com', 'instagram'),
  ('malenekrause@gmail.com', 'instagram'),
  ('sarahjbirch13@gmail.com', 'instagram'),
  ('maria.stettner.ms@gmail.com', 'instagram'),
  ('88-sonnenblumen@web.de', 'instagram'),
  ('palo.eerika@gmail.com', 'instagram'),
  ('bme116@me.com', 'instagram'),
  ('tanyagjacoby@gmail.com', 'instagram'),
  ('sergey@airmail.cc', 'instagram'),
  ('wuufje@gmail.com', 'instagram'),
  ('jaswindersira@gmail.com', 'instagram'),
  ('landofazlan@gmail.com', 'instagram'),
  ('yvonne_diehm@hotmail.com', 'instagram'),
  ('nicolepapp55@gmail.com', 'instagram'),
  ('alexroserizzle@gmail.com', 'instagram'),
  ('toussainthubert71@gmail.com', 'instagram'),
  ('timy20000526@gmail.com', 'instagram'),
  ('evorajandira@gmail.com', 'instagram'),
  ('leon06021997@gmail.com', 'instagram'),
  ('musunguaron6@gmail.com', 'instagram'),
  ('akshaykumarsetty3106@gmail.com', 'instagram'),
  ('aparnarao1212@gmail.com', 'instagram'),
  ('bkayode3@gmail.com', 'instagram'),
  ('kerryoconnor21@hotmail.co.uk', 'instagram'),
  ('aliciasgil@outlook.com', 'instagram'),
  ('nrw722@yahoo.com', 'instagram'),
  ('saidueng@gmail.com', 'instagram'),
  ('annamnjensen@outlook.dk', 'instagram'),
  ('iriawhiteosagie@gmail.com', 'instagram'),
  ('jamesconnauton01@outlook.com', 'instagram'),
  ('llamasgemelasunionesdivinas@gmail.com', 'instagram'),
  ('sonkar.akanksha2011@gmail.com', 'instagram'),
  ('quacogerald61@gmail.com', 'instagram'),
  ('jcperez07152020@gmail.com', 'instagram'),
  ('nemfrnzc@gmail.com', 'instagram'),
  ('nabeelzafar1128@gmail.com', 'instagram'),
  ('motherrobin@gmail.com', 'instagram'),
  ('barnesronnie501@proton.me', 'instagram'),
  ('kez8t2@hotmail.co.uk', 'instagram'),
  ('tomomewoadewaleed@gmail.com', 'instagram'),
  ('patronus411@gmail.com', 'instagram'),
  ('katarzyna.glowacka.84@gmail.com', 'instagram'),
  ('kitkat3333@aol.com', 'instagram'),
  ('minarulina81@gmail.com', 'instagram'),
  ('tarynmckee1955@gmail.com', 'instagram'),
  ('deborahvanetten109@gmail.com', 'instagram'),
  ('1roseofsharon243050@gmail.com', 'instagram'),
  ('bailey_321@outlook.com', 'instagram'),
  ('yungzay1485@gmail.com', 'instagram'),
  ('kelmar22@yahoo.com', 'instagram'),
  ('akshaykumarsetty3831@gmail.com', 'instagram'),
  ('klevelive@hotmail.com', 'instagram'),
  ('joelhertzinger@yahoo.com', 'instagram'),
  ('mintkeeper@icloud.com', 'instagram'),
  ('fhasannia91@yahoo.com', 'instagram'),
  ('anessiasamuel@gmail.com', 'instagram'),
  ('minchixboss@gmail.com', 'instagram'),
  ('hbrightlysf@gmail.com', 'instagram'),
  ('sixortega00@gmail.com', 'instagram'),
  ('jp.chavez9@me.com', 'instagram'),
  ('peteguzman02@yahoo.com', 'instagram'),
  ('ajaymadathil8@gmail.com', 'instagram'),
  ('matty454ss@gmail.com', 'instagram'),
  ('amanda@amandawilbanks.net', 'instagram'),
  ('mnepair@gmail.com', 'instagram'),
  ('dinizlueji@gmail.com', 'instagram'),
  ('thindsukhi@icloud.com', 'instagram'),
  ('bgregmarie1@yahoo.com', 'instagram'),
  ('eric.rayshawn27@gmail.com', 'instagram'),
  ('simoneifransuamartinez@gmail.com', 'instagram'),
  ('divyavijaylaxmisingh@gmail.com', 'instagram'),
  ('divyavijaylaxmisingj@gmail.com', 'instagram'),
  ('kumarakhilesh95978@gmail.com', 'instagram'),
  ('ssn.hhn@gmail.com', 'instagram'),
  ('olleczka9098@gmail.com', 'instagram'),
  ('tyflowerguy@gmail.com', 'instagram'),
  ('ignatius444333@gmail.com', 'instagram')
ON CONFLICT (email) DO NOTHING;

-- Verify
SELECT source, COUNT(*) FROM public.api_leads GROUP BY source ORDER BY source;